import { useState } from 'react';
import { BrowserRouter, useNavigate } from 'react-router-dom';
import {
  ArrowRight, ArrowUpRight, Bike, Building2, Calculator, Check,
  CheckCircle2, Clock3, HeartHandshake, MapPin, Menu, PackageCheck,
  Recycle, ShieldCheck, Sparkles, Truck, Utensils, X,
} from 'lucide-react';
import './index.css';

type Role = 'donor' | 'shelter' | 'volunteer';

const steps = [
  ['01', 'Post surplus', 'Add the food, quantity, and pickup window in under 60 seconds.', Utensils],
  ['02', 'Get matched', 'Nearby shelters surface the rescue that fits their capacity right now.', MapPin],
  ['03', 'Coordinate pickup', 'A verified volunteer accepts the route and keeps everyone in sync.', Truck],
  ['04', 'Deliver impact', 'Every meal arrives safely, with a clear record of the rescue.', HeartHandshake],
] as const;

const roleContent: Record<Role, { eyebrow: string; title: string; copy: string; button: string }> = {
  donor: { eyebrow: 'FOOD DONOR PORTAL', title: "Turn tonight's extra into someone's next meal.", copy: 'Post cooked meals, bakery stock, or event surplus. Rescue handles the match and pickup coordination.', button: 'Post a donation' },
  shelter: { eyebrow: 'SHELTER PORTAL', title: 'Bring fresh surplus straight to your residents.', copy: 'Share your capacity and dietary needs, then claim nearby food before its best-by window closes.', button: 'Request food' },
  volunteer: { eyebrow: 'VOLUNTEER ROUTES', title: 'Make one small trip matter today.', copy: 'Pick up a verified route near you, follow the handoff, and see the impact land in real time.', button: 'See a route' },
};

function Brand({ onClick }: { onClick?: () => void }) {
  return <button className="brand" onClick={onClick} aria-label="Rescue home"><span className="brand-mark"><Recycle size={18} strokeWidth={2.6} /></span><span>rescue<span className="brand-dot">.</span></span></button>;
}

function LandingPage() {
  const navigate = useNavigate();
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeRole, setActiveRole] = useState<Role>('donor');
  const [modalRole, setModalRole] = useState<Role | null>(null);
  const [submitted, setSubmitted] = useState(false);
  const [kgPerDay, setKgPerDay] = useState('25');
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const numericKg = Number(kgPerDay) || 0;
  const meals = Math.round(numericKg * 2.2 * 30);
  const co2 = Math.round(numericKg * 2.5 * 30);
  const role = roleContent[activeRole];
  const openModal = (nextRole: Role) => { setModalRole(nextRole); setSubmitted(false); setMenuOpen(false); };
  const submitForm = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (email.trim()) setSubmitted(true); };

  return <div className="site-shell">
    <header className="site-nav shell-width"><Brand /><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How it works</a><a href="#impact" onClick={() => setMenuOpen(false)}>Our impact</a><a href="#roles" onClick={() => setMenuOpen(false)}>For partners</a><button className="nav-cta" onClick={() => openModal('donor')}>Join the network <ArrowUpRight size={15} /></button></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></header>
    <main>
      <section className="hero shell-width"><div className="hero-copy reveal"><div className="eyebrow"><span className="pulse" /> LIVE ACROSS BENGALURU</div><h1>Good food.<br /><em>Right place.</em><br />Right now.</h1><p className="hero-text">Rescue connects surplus food from local kitchens with shelters and neighbors who need it, before the clock runs out.</p><div className="hero-actions"><button className="button button-primary" onClick={() => openModal('donor')}>Donate surplus <ArrowRight size={16} /></button><a className="text-link" href="#roles">Explore the network <span>↗</span></a></div><div className="trusted"><div className="avatar-stack"><span className="avatar av-one">M</span><span className="avatar av-two">J</span><span className="avatar av-three">S</span><span className="avatar av-four">+</span></div><span>Trusted by <strong>480+ local partners</strong></span></div></div>
        <div className="flow-visual" aria-label="Live route from a kitchen to a shelter"><div className="flow-kicker"><span className="pulse" /> LIVE ROUTE · 07 MIN LEFT</div><svg className="flow-lines" viewBox="0 0 640 510" preserveAspectRatio="none" aria-hidden="true"><path className="flow-glow" d="M75 145 C190 85 230 290 360 235 S490 110 570 160" /><path className="flow-track" d="M75 145 C190 85 230 290 360 235 S490 110 570 160" /><path className="flow-track secondary-track" d="M95 380 C205 450 330 335 410 375 S510 425 590 350" /></svg><div className="flow-node flow-restaurant"><span className="flow-node-icon"><Utensils size={17} /></span><span><strong>Olive & Grain</strong><small>15 kg ready</small></span></div><div className="flow-node flow-driver"><span className="flow-node-icon"><Bike size={17} /></span><span><strong>Amara · en route</strong><small>Volunteer driver</small></span></div><div className="flow-node flow-ngo"><span className="flow-node-icon"><HeartHandshake size={17} /></span><span><strong>Harbor House</strong><small>Receiving now</small></span></div><span className="flow-annotation annotation-one">FRESH · VERIFIED · MOVING</span><span className="flow-annotation annotation-two">ONE CITY / MANY HANDS</span><div className="flow-status"><span className="pulse" /> COORDINATED IN REAL TIME</div></div>
      </section>
      <div className="ticker"><div className="ticker-inner shell-width"><span>EVERY RESCUE COUNTS</span><i /> <strong>23,841 KG</strong><span>KEPT IN USE THIS MONTH</span><span className="ticker-heart">♥</span><span>BUILT BY NEIGHBORS</span></div></div>
      <section className="section-grid shell-width"><div className="section-intro"><div className="eyebrow">THE GAP IS REAL</div><h2>There is enough food.<br /><em>It just needs to move.</em></h2></div><div><p className="large-copy">Every day, perfectly good food leaves commercial kitchens while nearby shelters go without. The missing piece is a real-time connection between <strong>surplus, timing, distance, and capacity.</strong></p><div className="stat-pills"><div><strong>40%</strong><span>of food is wasted</span></div><div><strong>1 in 8</strong><span>face food insecurity</span></div></div></div></section>
      <section className="solution shell-width" id="how-it-works"><div className="solution-heading"><div><div className="eyebrow">THE RESCUE NETWORK</div><h2>From surplus<br /><em>to shared.</em></h2></div><p>One simple loop for the exact moments when good food needs somewhere to go.</p></div><div className="steps">{steps.map(([number, title, text, Icon]) => <article className="step" key={number}><span className="step-number">{number}</span><span className="step-icon"><Icon size={20} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="live-section"><div className="live-wrap shell-width"><div className="live-copy"><div className="eyebrow light"><span className="pulse" /> THE NETWORK IS MOVING</div><h2>Good things<br /><em>in motion.</em></h2><p>Every listing is matched by distance, dietary fit, urgency, and verified capacity. No cold spreadsheets. No guesswork.</p><button className="button button-light" onClick={() => openModal('volunteer')}>See a live route <ArrowRight size={16} /></button></div><div className="network-card"><div className="network-header"><span><span className="status-dot green" /> ACTIVE RESCUES</span><span>BENGALURU · NOW</span></div><div className="map-grid"><span className="map-line line-a" /><span className="map-line line-b" /><span className="map-line line-c" /><span className="map-pin pin-a"><Utensils size={14} /></span><span className="map-pin pin-b"><Bike size={14} /></span><span className="map-pin pin-c"><HeartHandshake size={14} /></span><span className="map-center"><Recycle size={18} /></span></div><div className="network-footer"><div><strong>18</strong>active handoffs</div><div><strong>4.2 km</strong>average route</div><div><strong>96%</strong>on time</div></div></div></div></section>
      <section className="roles shell-width" id="roles"><div className="center-heading"><div className="eyebrow">THERE IS A PLACE FOR YOU HERE</div><h2>Many hands.<br /><em>One shared table.</em></h2><p>Choose your way into the network. The first rescue can start in under a minute.</p></div><div className="role-grid">{(Object.keys(roleContent) as Role[]).map((key) => { const Icon = key === 'donor' ? Utensils : key === 'shelter' ? Building2 : Bike; return <button className={activeRole === key ? 'role-card active' : 'role-card'} key={key} onClick={() => { setActiveRole(key); if (key === 'volunteer') openModal(key); }}><span className="role-icon"><Icon size={22} /></span><span className="eyebrow">{roleContent[key].eyebrow}</span><h3>{roleContent[key].title}</h3><p>{roleContent[key].copy}</p><span className="arrow-link">{roleContent[key].button} <ArrowRight size={15} /></span></button>; })}</div><div className="role-detail"><div><div className="eyebrow">{role.eyebrow}</div><h3>{role.title}</h3><p>{role.copy}</p></div><button className="button button-primary" onClick={() => openModal(activeRole)}>{role.button} <ArrowRight size={16} /></button></div></section>
      <section className="impact shell-width" id="impact"><div className="impact-heading"><div className="eyebrow">SMALL ACTIONS, VISIBLE CHANGE</div><h2>The numbers<br /><em>tell the story.</em></h2><p>A rescue is small to one person and enormous to the person receiving it.</p></div><div className="impact-stats"><div className="impact-stat"><span className="impact-icon"><PackageCheck size={18} /></span><strong>186,420</strong><span>kg food rescued</span></div><div className="impact-stat"><span className="impact-icon"><HeartHandshake size={18} /></span><strong>421,800</strong><span>meals shared</span></div><div className="impact-stat"><span className="impact-icon"><ShieldCheck size={18} /></span><strong>9,240</strong><span>successful rescues</span></div><div className="impact-stat"><span className="impact-icon"><Clock3 size={18} /></span><strong>480+</strong><span>local partners</span></div></div></section>
      <section className="calculator shell-width"><div><div className="eyebrow"><Calculator size={13} /> IMPACT ESTIMATOR</div><h2>Make the<br /><em>math visible.</em></h2><p>Tell us what your kitchen could rescue on an average day.</p></div><div className="calc-card"><div className="calc-header"><Utensils size={18} /> Daily surplus estimator</div><label htmlFor="kg">AVERAGE DAILY SURPLUS (KG)</label><div className="calc-input-wrap"><input id="kg" type="number" min="0" value={kgPerDay} onChange={(event) => setKgPerDay(event.target.value)} /><span>kg / day</span></div><div className="calc-results"><div><strong>{meals.toLocaleString()}</strong><span>MEALS / MONTH</span></div><div><strong>{co2.toLocaleString()} kg</strong><span>CO2 PREVENTED</span></div></div><div className="calc-note"><CheckCircle2 size={15} /> Based on 2.2 meals and 2.5 kg CO2 saved per kg rescued.</div></div></section>
      <section className="join shell-width"><div className="join-inner"><div><div className="eyebrow">START WITH ONE RESCUE</div><h2>Nothing good<br /><em>goes to waste.</em></h2></div><div className="join-side"><p>Join a practical, local network for kitchens, shelters, and volunteer drivers.</p><button className="button button-primary" onClick={() => openModal('donor')}>Join the rescue network <ArrowRight size={16} /></button><small>Free to join · verified partners only</small></div></div></section>
    </main>
    <footer className="footer shell-width"><Brand onClick={() => navigate('/')} /><span>© 2026 FoodShelter Connect</span><div><a href="#how-it-works">How it works</a><a href="#impact">Impact</a><a href="#roles">Partners</a></div></footer>
    {modalRole && <div className="modal-overlay" onClick={() => setModalRole(null)}><div className="modal-card" onClick={(event) => event.stopPropagation()}><div className="modal-header"><div><div className="eyebrow"><Sparkles size={13} /> {roleContent[modalRole].eyebrow}</div><h3>{roleContent[modalRole].title}</h3></div><button className="icon-button" onClick={() => setModalRole(null)} aria-label="Close"><X size={20} /></button></div>{submitted ? <div className="modal-success"><span><Check size={25} /></span><h3>You are on the list.</h3><p>We will send the next step to {email}.</p><button className="button button-primary" onClick={() => navigate('/dashboard')}>Open your dashboard <ArrowRight size={15} /></button></div> : <form onSubmit={submitForm}><p className="modal-copy">{roleContent[modalRole].copy}</p><label htmlFor="name">NAME OR ORGANIZATION</label><input id="name" value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Royal Spice Kitchen" /><label htmlFor="email">EMAIL ADDRESS</label><input id="email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="hello@example.com" /><button className="modal-submit" type="submit">Request access <ArrowRight size={16} /></button></form>}</div></div>}
  </div>;
}

function Dashboard() {
  const navigate = useNavigate();
  return <div className="dashboard"><header className="site-nav shell-width"><Brand onClick={() => navigate('/')} /><div className="dashboard-label"><span className="status-dot green" /> RESCUE CONTROL ROOM</div></header><main className="dashboard-main shell-width"><div className="dashboard-heading"><div><div className="eyebrow">GOOD AFTERNOON, ROYAL SPICE</div><h1>Your rescue board.</h1><p>One live donation. Two nearby shelters. Plenty of good still in motion.</p></div><button className="button button-primary" onClick={() => navigate('/')}>Back to overview <ArrowRight size={15} /></button></div><div className="dashboard-grid"><section className="dashboard-card live-donation"><div className="card-topline"><span className="status-chip"><span className="pulse" /> MATCHING NOW</span><span>POSTED 15 MIN AGO</span></div><h2>Veg biryani & 30 rotis</h2><p className="muted">Cooked meals · Serves ~30 people · 12 kg</p><div className="route-summary"><div><span className="route-badge orange"><Utensils size={16} /></span><strong>Royal Spice Kitchen</strong><small>Indiranagar · pickup ready</small></div><ArrowRight size={18} /><div><span className="route-badge teal"><Building2 size={16} /></span><strong>Harbor House Shelter</strong><small>1.8 km · needs dinner meals</small></div></div><div className="progress-track"><span /></div><div className="progress-labels"><span>Listing live</span><span>Volunteer matching</span><span>Delivered</span></div></section><section className="dashboard-card"><div className="card-topline"><span className="eyebrow">THIS MONTH</span><span className="trend">+18%</span></div><div className="big-stat">120 <small>meals shared</small></div><div className="mini-stats"><div><strong>48 kg</strong><span>food rescued</span></div><div><strong>3.2 kg</strong><span>CO2 prevented</span></div></div><button className="outline-button"><ShieldCheck size={15} /> Download impact log</button></section><section className="dashboard-card nearby"><div className="card-topline"><span className="eyebrow">NEARBY NEEDS</span><span>2 MATCHES</span></div><div className="need-row"><span className="route-badge lime"><HeartHandshake size={16} /></span><div><strong>Harbor House Shelter</strong><small>Needs 50 veg meals · by 7:30 PM</small></div><MapPin size={16} /></div><div className="need-row"><span className="route-badge purple"><Building2 size={16} /></span><div><strong>Sunrise Orphanage</strong><small>Needs snacks for 45 children</small></div><MapPin size={16} /></div></section></div></main></div>;
}

export default function App() { return <BrowserRouter><RoutesFallback /></BrowserRouter>; }
function RoutesFallback() { return window.location.pathname === '/dashboard' ? <Dashboard /> : <LandingPage />; }